import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { NavLink } from "react-router-dom";
import { LayoutDashboard, Video, FileCode2, BarChart3, History, Layers, ChevronLeft, ChevronRight, Settings, } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { useDashboardStore } from "@/store/useDashboardStore";
const navItems = [
    { to: "/", label: "Dashboard", icon: LayoutDashboard, end: true },
    { to: "/videos", label: "Videos", icon: Video },
    { to: "/patches", label: "Patches", icon: FileCode2 },
    { to: "/reports", label: "Reports", icon: BarChart3 },
    { to: "/history", label: "History", icon: History },
];
export default function AppSidebar() {
    const { sidebarOpen, toggleSidebar, setMobileMenuOpen } = useDashboardStore();
    return (_jsxs("aside", { role: "navigation", "aria-label": "Main navigation", className: `fixed top-0 left-0 bottom-0 z-40 glass-sidebar flex flex-col transition-[width] duration-300 ease-out ${sidebarOpen ? "w-60" : "w-[72px]"}`, children: [_jsxs("div", { className: "h-16 flex items-center justify-between px-3.5 border-b border-border/40 shrink-0", children: [_jsxs("div", { className: "flex items-center gap-3 min-w-0 overflow-hidden", children: [_jsx("div", { className: "w-9 h-9 rounded-xl bg-gradient-to-br from-primary to-purple-600 flex items-center justify-center text-white shadow-glow shrink-0", children: _jsx(Layers, { className: "w-5 h-5", "aria-hidden": "true" }) }), _jsx(AnimatePresence, { children: sidebarOpen && (_jsx(motion.div, { initial: { opacity: 0, width: 0 }, animate: { opacity: 1, width: "auto" }, exit: { opacity: 0, width: 0 }, transition: { duration: 0.2 }, className: "flex flex-col overflow-hidden", children: _jsxs("span", { className: "font-extrabold text-sm text-text tracking-tight whitespace-nowrap flex items-center gap-1.5", children: ["PatchFlow", _jsx("span", { className: "text-[10px] uppercase tracking-wider font-semibold px-1.5 py-0.5 rounded bg-primary/20 text-primary border border-primary/30", children: "PRO" })] }) })) })] }), _jsx(motion.button, { type: "button", whileHover: { scale: 1.08 }, whileTap: { scale: 0.93 }, onClick: toggleSidebar, "aria-label": sidebarOpen ? "Collapse sidebar" : "Expand sidebar", className: "hidden md:flex p-1.5 rounded-lg text-muted hover:text-text hover:bg-white/8 border border-transparent hover:border-white/10 transition-all shrink-0 focus-visible:ring-2 focus-visible:ring-primary/40", children: sidebarOpen ? (_jsx(ChevronLeft, { className: "w-4 h-4", "aria-hidden": "true" })) : (_jsx(ChevronRight, { className: "w-4 h-4", "aria-hidden": "true" })) })] }), _jsx("nav", { className: "flex-1 px-2.5 py-4 space-y-1 overflow-y-auto overflow-x-hidden", children: navItems.map((item) => {
                    const Icon = item.icon;
                    return (_jsx(NavLink, { to: item.to, end: item.end, onClick: () => setMobileMenuOpen(false), className: ({ isActive }) => `relative flex items-center gap-3 px-2.5 py-2.5 rounded-xl text-sm font-medium transition-all group focus-visible:ring-2 focus-visible:ring-primary/40 ${isActive
                            ? "bg-primary/12 text-text border border-primary/28"
                            : "text-muted hover:text-text hover:bg-white/5 border border-transparent hover:border-white/8"}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [isActive && (_jsx(motion.div, { layoutId: "activeIndicator", className: "absolute left-0 top-2 bottom-2 w-[3px] bg-primary rounded-r-full", style: { boxShadow: "0 0 10px rgba(124,58,237,0.7)" }, transition: { type: "spring", stiffness: 380, damping: 28 } })), _jsx(Icon, { className: `w-5 h-5 shrink-0 transition-colors ${isActive ? "text-primary" : "text-muted group-hover:text-text"}`, "aria-hidden": "true" }), _jsx(AnimatePresence, { children: sidebarOpen && (_jsx(motion.span, { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, transition: { duration: 0.15 }, className: "truncate", children: item.label })) }), !sidebarOpen && (_jsx("div", { role: "tooltip", className: "pointer-events-none absolute left-full ml-3 px-2.5 py-1.5 rounded-lg bg-card/90 border border-border text-xs font-semibold text-text whitespace-nowrap opacity-0 group-hover:opacity-100 transition-opacity shadow-xl z-50", children: item.label }))] })) }, item.to));
                }) }), _jsx("div", { className: "p-2.5 border-t border-border/40 shrink-0", children: sidebarOpen ? (_jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, className: "glass-card rounded-xl p-3 flex items-center justify-between gap-2 hover:border-white/18 transition-all", children: [_jsxs("div", { className: "flex items-center gap-2.5 min-w-0", children: [_jsx("div", { className: "w-8 h-8 rounded-full bg-gradient-to-tr from-purple-500 to-indigo-600 flex items-center justify-center text-xs font-bold text-white shrink-0", children: "JD" }), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "text-xs font-semibold text-text truncate", children: "Jane Doe" }), _jsx("p", { className: "text-[11px] text-muted truncate", children: "jane@patchflow.io" })] })] }), _jsx(motion.button, { type: "button", whileHover: { rotate: 45 }, transition: { type: "spring", stiffness: 400, damping: 20 }, "aria-label": "Open settings", className: "text-muted hover:text-text p-1.5 rounded-lg hover:bg-white/8 transition shrink-0 focus-visible:ring-2 focus-visible:ring-primary/40", children: _jsx(Settings, { className: "w-4 h-4", "aria-hidden": "true" }) })] })) : (_jsx("div", { className: "flex justify-center py-1", children: _jsx("div", { className: "w-9 h-9 rounded-full bg-gradient-to-tr from-purple-500 to-indigo-600 flex items-center justify-center text-xs font-bold text-white", children: "JD" }) })) })] }));
}
