import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { History, ChevronDown, ChevronRight, CheckCircle2, FileCode2, User, Calendar, Layers, ArrowUpRight, Plus, } from "lucide-react";
import { usePatchStore } from "@/store/usePatchStore";
const containerVariants = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.07 } },
};
const itemVariants = {
    hidden: { y: 14, opacity: 0 },
    visible: { y: 0, opacity: 1, transition: { type: "spring", stiffness: 280, damping: 22 } },
};
export default function HistoryPage() {
    const { patchHistory, currentVideoTitle } = usePatchStore();
    const [expanded, setExpanded] = useState(patchHistory[patchHistory.length - 1]?.id ?? null);
    return (_jsxs(motion.div, { variants: containerVariants, initial: "hidden", animate: "visible", className: "max-w-4xl mx-auto space-y-8 pb-16", children: [_jsxs(motion.div, { variants: itemVariants, className: "space-y-2", children: [_jsxs("div", { className: "inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-xs font-semibold text-primary", children: [_jsx(History, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "Version History" })] }), _jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl md:text-4xl font-extrabold text-text tracking-tight", children: "Patch Timeline" }), _jsxs("p", { className: "text-muted text-sm mt-1", children: ["All patch versions for ", _jsx("span", { className: "text-text font-medium", children: currentVideoTitle })] })] }), _jsxs(Link, { to: "/create-patch", className: "inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-primary to-purple-600 hover:from-primary-hover text-white font-semibold text-sm shadow-glow transition-all shrink-0", children: [_jsx(Plus, { className: "w-4 h-4" }), " New Patch"] })] })] }), _jsxs(motion.div, { variants: itemVariants, className: "relative", children: [_jsx("div", { className: "absolute left-5 top-8 bottom-8 w-0.5 bg-gradient-to-b from-primary/40 via-border to-transparent" }), _jsx("div", { className: "space-y-4", children: patchHistory.map((entry, idx) => {
                            const isLatest = idx === patchHistory.length - 1;
                            const isExpanded = expanded === entry.id;
                            const isOriginal = entry.occurrences === 0;
                            return (_jsxs(motion.div, { initial: { opacity: 0, x: -8 }, animate: { opacity: 1, x: 0 }, transition: { delay: idx * 0.07 }, className: "relative pl-12", children: [_jsx("div", { className: `absolute left-3.5 top-4 w-4 h-4 rounded-full border-2 flex items-center justify-center ${isLatest
                                            ? "bg-primary border-primary shadow-glow"
                                            : isOriginal
                                                ? "bg-surface border-border"
                                                : "bg-emerald-500 border-emerald-500"}`, children: isLatest && _jsx("div", { className: "w-1.5 h-1.5 rounded-full bg-white animate-ping" }) }), _jsxs("div", { className: "flex items-center gap-2 mb-1.5", children: [_jsx("span", { className: `text-xs font-mono font-bold px-2 py-0.5 rounded ${isLatest
                                                    ? "bg-primary/20 text-primary border border-primary/30"
                                                    : "bg-surface text-muted border border-border"}`, children: entry.version }), isLatest && (_jsx("span", { className: "text-[10px] font-semibold px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20", children: "Latest" }))] }), _jsxs("div", { className: "glass-card rounded-2xl border border-border overflow-hidden", children: [_jsxs("button", { onClick: () => setExpanded(isExpanded ? null : entry.id), className: "w-full text-left flex items-center justify-between p-4 hover:bg-white/[0.02] transition", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: `w-9 h-9 rounded-xl flex items-center justify-center shrink-0 ${isOriginal
                                                                    ? "bg-surface text-muted border border-border"
                                                                    : "bg-emerald-500/10 text-emerald-400 border border-emerald-500/25"}`, children: isOriginal ? (_jsx(Layers, { className: "w-4 h-4" })) : (_jsx(CheckCircle2, { className: "w-4 h-4" })) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-bold text-text", children: isOriginal ? "Original Upload" : `Patch #${idx}` }), _jsx("p", { className: "text-xs text-muted truncate max-w-xs", children: isOriginal ? "Initial video asset — no patches applied" : entry.summary })] })] }), isExpanded ? (_jsx(ChevronDown, { className: "w-4 h-4 text-muted shrink-0" })) : (_jsx(ChevronRight, { className: "w-4 h-4 text-muted shrink-0" }))] }), isExpanded && !isOriginal && (_jsxs(motion.div, { initial: { opacity: 0, height: 0 }, animate: { opacity: 1, height: "auto" }, exit: { opacity: 0, height: 0 }, className: "border-t border-border p-4 space-y-4", children: [_jsxs("div", { className: "grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Calendar, { className: "w-3.5 h-3.5 text-muted" }), _jsx("span", { className: "text-muted", children: "Date:" }), _jsx("span", { className: "text-text font-medium", children: entry.date })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(User, { className: "w-3.5 h-3.5 text-muted" }), _jsx("span", { className: "text-muted", children: "Author:" }), _jsx("span", { className: "text-text font-medium", children: entry.author })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(FileCode2, { className: "w-3.5 h-3.5 text-muted" }), _jsx("span", { className: "text-muted", children: "Occurrences:" }), _jsx("span", { className: "text-text font-medium", children: entry.occurrences })] })] }), _jsxs("div", { className: "p-3 rounded-xl bg-card border border-border", children: [_jsx("p", { className: "text-xs font-mono text-muted/70 mb-1", children: "Command" }), _jsx("p", { className: "text-xs font-medium text-text", children: entry.command })] }), entry.assetsAffected.length > 0 && (_jsx("div", { className: "flex flex-wrap gap-2", children: entry.assetsAffected.map((a) => (_jsx("span", { className: "px-2.5 py-1 rounded-lg text-[11px] font-medium bg-primary/10 text-primary border border-primary/20", children: a }, a))) })), _jsxs(Link, { to: "/report", className: "inline-flex items-center gap-1.5 text-xs font-semibold text-primary hover:text-purple-300 transition", children: ["View Report ", _jsx(ArrowUpRight, { className: "w-3.5 h-3.5" })] })] }))] })] }, entry.id));
                        }) })] })] }));
}
